import { IAlbum } from './models';
export const PhotoLibrary: Array<IAlbum> = [
  {
    album: `By the Water`,
    statement: [""],
    images: [
      require(`@/assets/albums/By the Water/000003.jpg`),
      require(`@/assets/albums/By the Water/002.jpg`),
      require(`@/assets/albums/By the Water/003.jpg`),
      require(`@/assets/albums/By the Water/004.jpg`),
      require(`@/assets/albums/By the Water/005.jpg`),
      require(`@/assets/albums/By the Water/006.jpg`),
      require(`@/assets/albums/By the Water/007.jpg`),
      require(`@/assets/albums/By the Water/008.jpg`),
      require(`@/assets/albums/By the Water/009.jpg`),
      require(`@/assets/albums/By the Water/010.jpg`),
      require(`@/assets/albums/By the Water/011.jpg`),
      require(`@/assets/albums/By the Water/012.jpg`),
      require(`@/assets/albums/By the Water/013.jpg`),
      require(`@/assets/albums/By the Water/014.jpg`),
      require(`@/assets/albums/By the Water/015.jpg`),
      require(`@/assets/albums/By the Water/016.jpg`),
      require(`@/assets/albums/By the Water/017.jpg`),
      require(`@/assets/albums/By the Water/018.jpg`),
      require(`@/assets/albums/By the Water/019.jpg`),
      require(`@/assets/albums/By the Water/020.jpg`),
    ]
  },
  {
    album: `Happy Everyday`,
    statement: [""],
    images: [
      require(`@/assets/albums/Happy Everyday/01.jpg`),
      require(`@/assets/albums/Happy Everyday/02.jpg`),
      require(`@/assets/albums/Happy Everyday/03.jpg`),
      require(`@/assets/albums/Happy Everyday/04.jpg`),
      require(`@/assets/albums/Happy Everyday/05.jpg`),
      require(`@/assets/albums/Happy Everyday/06.jpg`),
      require(`@/assets/albums/Happy Everyday/07.jpg`),
      require(`@/assets/albums/Happy Everyday/08.jpg`),
      require(`@/assets/albums/Happy Everyday/09.jpg`),
      require(`@/assets/albums/Happy Everyday/10.jpg`),
      require(`@/assets/albums/Happy Everyday/11.jpg`),
      require(`@/assets/albums/Happy Everyday/12.jpg`),
      require(`@/assets/albums/Happy Everyday/13.jpg`),
      require(`@/assets/albums/Happy Everyday/14.jpg`),
      require(`@/assets/albums/Happy Everyday/15.jpg`),
      require(`@/assets/albums/Happy Everyday/16.jpg`),
      require(`@/assets/albums/Happy Everyday/17.jpg`),
      require(`@/assets/albums/Happy Everyday/18.jpg`),
      require(`@/assets/albums/Happy Everyday/19.jpg`),
      require(`@/assets/albums/Happy Everyday/20.jpg`),
      require(`@/assets/albums/Happy Everyday/21.jpg`),
      require(`@/assets/albums/Happy Everyday/22.jpg`),
      require(`@/assets/albums/Happy Everyday/23.jpg`),
      require(`@/assets/albums/Happy Everyday/24.jpg`),
      require(`@/assets/albums/Happy Everyday/25.jpg`),
      require(`@/assets/albums/Happy Everyday/26.jpg`),
    ]
  },
  {
    album: `Message from Dawn`,
    statement: ["I was only very little when my older brother ran away from home. It took years for my family to convince him to return, but towards everyone he became very distant. To me, he was virtually a stranger. In this personal project, I tried to establish a connection between me and my detached brother - based on clues I found around the house and interviews with my parents or people who knew him. Retracing the journey my brother went through after he left our family, I've come to realize that we have a lot more in common than I think."],
    images: [
      require(`@/assets/albums/Message from Dawn/01.jpg`),
      require(`@/assets/albums/Message from Dawn/02.jpg`),
      require(`@/assets/albums/Message from Dawn/03.jpg`),
      require(`@/assets/albums/Message from Dawn/04.jpg`),
      require(`@/assets/albums/Message from Dawn/05.jpg`),
      require(`@/assets/albums/Message from Dawn/06.jpg`),
      require(`@/assets/albums/Message from Dawn/07.jpg`),
      require(`@/assets/albums/Message from Dawn/08.jpg`),
    ]
  },
  {
    album: `Table for One`,
    statement: [""],
    images: [
      require(`@/assets/albums/Table for One/01.jpg`),
      require(`@/assets/albums/Table for One/02.jpg`),
      require(`@/assets/albums/Table for One/03.jpg`),
      require(`@/assets/albums/Table for One/04.jpg`),
      require(`@/assets/albums/Table for One/05.jpg`),
      require(`@/assets/albums/Table for One/06.jpg`),
      require(`@/assets/albums/Table for One/07.jpg`),
      require(`@/assets/albums/Table for One/08.jpg`),
      require(`@/assets/albums/Table for One/09.jpg`),
      require(`@/assets/albums/Table for One/10.jpg`),
      require(`@/assets/albums/Table for One/11.jpg`),
      require(`@/assets/albums/Table for One/12.jpg`),
      require(`@/assets/albums/Table for One/13.jpg`),
    ]
  },
  {
    album: `The Land of Choice`,
    statement: ["Dak R'Mang, a ward in the province of Dak Nong, central highlands Vietnam is a very peculiar land - being home to a concentration of more than 20 ethnic minortities, all of whom migrated here during the \"New Economics\" wave. ","As part of a residency program, I had the opportunity to stay within a community of ethnic minority settlers, for the purpose of documenting their daily life. I embarked on this journey with a curiosity about the people's indigenous knowledge, about the choices that brought them here, and most importantly - a very personal belief that traditional values when placed in a foreign setting will give birth to very interesting phenomenon."],
    images: [
      require(`@/assets/albums/The Land of Choice/001.jpg`),
      require(`@/assets/albums/The Land of Choice/002.jpg`),
      require(`@/assets/albums/The Land of Choice/003.jpg`),
      require(`@/assets/albums/The Land of Choice/004.jpg`),
      require(`@/assets/albums/The Land of Choice/005.jpg`),
      require(`@/assets/albums/The Land of Choice/006.jpg`),
      require(`@/assets/albums/The Land of Choice/007.jpg`),
      require(`@/assets/albums/The Land of Choice/008.jpg`),
      require(`@/assets/albums/The Land of Choice/009.jpg`),
      require(`@/assets/albums/The Land of Choice/010.jpg`),
      require(`@/assets/albums/The Land of Choice/011.jpg`),
      require(`@/assets/albums/The Land of Choice/012.jpg`),
      require(`@/assets/albums/The Land of Choice/013.jpg`),
      require(`@/assets/albums/The Land of Choice/014.jpg`),
      require(`@/assets/albums/The Land of Choice/015.jpg`),
      require(`@/assets/albums/The Land of Choice/016.jpg`),
      require(`@/assets/albums/The Land of Choice/017.jpg`),
      require(`@/assets/albums/The Land of Choice/018.jpg`),
      require(`@/assets/albums/The Land of Choice/019.jpg`),
    ]
  },
];
